# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_with_tabs.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName(_fromUtf8("TabWidget"))
        TabWidget.resize(1351, 987)
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.benchmarks = QtGui.QLabel(self.tab)
        self.benchmarks.setGeometry(QtCore.QRect(30, 140, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.benchmarks.setFont(font)
        self.benchmarks.setObjectName(_fromUtf8("benchmarks"))
        self.benchmark_profiles_2 = QtGui.QLabel(self.tab)
        self.benchmark_profiles_2.setGeometry(QtCore.QRect(20, 370, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.benchmark_profiles_2.setFont(font)
        self.benchmark_profiles_2.setObjectName(_fromUtf8("benchmark_profiles_2"))
        self.chart_type = QtGui.QLabel(self.tab)
        self.chart_type.setGeometry(QtCore.QRect(10, 540, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.chart_type.setFont(font)
        self.chart_type.setObjectName(_fromUtf8("chart_type"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 70, 461, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.python_2_cb = QtGui.QCheckBox(self.layoutWidget)
        self.python_2_cb.setObjectName(_fromUtf8("python_2_cb"))
        self.horizontalLayout.addWidget(self.python_2_cb)
        self.python_3_cb = QtGui.QCheckBox(self.layoutWidget)
        self.python_3_cb.setObjectName(_fromUtf8("python_3_cb"))
        self.horizontalLayout.addWidget(self.python_3_cb)
        self.bar_chart_rb = QtGui.QRadioButton(self.tab)
        self.bar_chart_rb.setGeometry(QtCore.QRect(10, 580, 111, 22))
        self.bar_chart_rb.setObjectName(_fromUtf8("bar_chart_rb"))
        self.python_interpreter = QtGui.QLabel(self.tab)
        self.python_interpreter.setGeometry(QtCore.QRect(30, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.python_interpreter.setFont(font)
        self.python_interpreter.setObjectName(_fromUtf8("python_interpreter"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 410, 391, 41))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.benchmark_profile_time_rb = QtGui.QRadioButton(self.layoutWidget_2)
        self.benchmark_profile_time_rb.setObjectName(_fromUtf8("benchmark_profile_time_rb"))
        self.horizontalLayout_2.addWidget(self.benchmark_profile_time_rb)
        self.iterations = QtGui.QLabel(self.tab)
        self.iterations.setGeometry(QtCore.QRect(20, 460, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.iterations.setFont(font)
        self.iterations.setObjectName(_fromUtf8("iterations"))
        self.iterations_value = QtGui.QTextEdit(self.tab)
        self.iterations_value.setGeometry(QtCore.QRect(20, 500, 161, 31))
        self.iterations_value.setObjectName(_fromUtf8("iterations_value"))
        self.analyze_button = QtGui.QPushButton(self.tab)
        self.analyze_button.setGeometry(QtCore.QRect(510, 610, 99, 27))
        self.analyze_button.setObjectName(_fromUtf8("analyze_button"))
        self.progressBar = QtGui.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(500, 650, 118, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.layoutWidget_3 = QtGui.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 180, 481, 41))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.benchmark_exceptions_rb = QtGui.QRadioButton(self.layoutWidget_3)
        self.benchmark_exceptions_rb.setObjectName(_fromUtf8("benchmark_exceptions_rb"))
        self.horizontalLayout_5.addWidget(self.benchmark_exceptions_rb)
        self.benchmark_list_compr_rb = QtGui.QRadioButton(self.layoutWidget_3)
        self.benchmark_list_compr_rb.setObjectName(_fromUtf8("benchmark_list_compr_rb"))
        self.horizontalLayout_5.addWidget(self.benchmark_list_compr_rb)
        self.benchmark_generators_rb = QtGui.QRadioButton(self.layoutWidget_3)
        self.benchmark_generators_rb.setObjectName(_fromUtf8("benchmark_generators_rb"))
        self.horizontalLayout_5.addWidget(self.benchmark_generators_rb)
        self.benchmarks_2 = QtGui.QLabel(self.tab)
        self.benchmarks_2.setGeometry(QtCore.QRect(30, 240, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.benchmarks_2.setFont(font)
        self.benchmarks_2.setObjectName(_fromUtf8("benchmarks_2"))
        self.load_file_button = QtGui.QPushButton(self.tab)
        self.load_file_button.setGeometry(QtCore.QRect(50, 290, 151, 61))
        self.load_file_button.setObjectName(_fromUtf8("load_file_button"))
        self.front_image = QtGui.QLabel(self.tab)
        self.front_image.setGeometry(QtCore.QRect(740, 140, 461, 401))
        self.front_image.setObjectName(_fromUtf8("front_image"))
        self.python_interpreter_7 = QtGui.QLabel(self.tab)
        self.python_interpreter_7.setGeometry(QtCore.QRect(730, 20, 481, 91))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.python_interpreter_7.setFont(font)
        self.python_interpreter_7.setObjectName(_fromUtf8("python_interpreter_7"))
        TabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1311, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.python_interpreter_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.python_interpreter_2.setFont(font)
        self.python_interpreter_2.setObjectName(_fromUtf8("python_interpreter_2"))
        self.horizontalLayout_3.addWidget(self.python_interpreter_2)
        self.python_interpreter_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.python_interpreter_3.setFont(font)
        self.python_interpreter_3.setObjectName(_fromUtf8("python_interpreter_3"))
        self.horizontalLayout_3.addWidget(self.python_interpreter_3)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 1311, 601))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.bytecode_python2 = QtGui.QPlainTextEdit(self.horizontalLayoutWidget_2)
        self.bytecode_python2.setObjectName(_fromUtf8("bytecode_python2"))
        self.horizontalLayout_4.addWidget(self.bytecode_python2)
        self.bytecode_python3 = QtGui.QPlainTextEdit(self.horizontalLayoutWidget_2)
        self.bytecode_python3.setObjectName(_fromUtf8("bytecode_python3"))
        self.horizontalLayout_4.addWidget(self.bytecode_python3)
        TabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.chart_label = QtGui.QLabel(self.tab_3)
        self.chart_label.setGeometry(QtCore.QRect(10, 150, 421, 341))
        self.chart_label.setObjectName(_fromUtf8("chart_label"))
        self.benchmark_profile_output_2 = QtGui.QPlainTextEdit(self.tab_3)
        self.benchmark_profile_output_2.setGeometry(QtCore.QRect(440, 80, 441, 511))
        self.benchmark_profile_output_2.setObjectName(_fromUtf8("benchmark_profile_output_2"))
        self.benchmark_profile_output_3 = QtGui.QPlainTextEdit(self.tab_3)
        self.benchmark_profile_output_3.setGeometry(QtCore.QRect(890, 80, 441, 511))
        self.benchmark_profile_output_3.setObjectName(_fromUtf8("benchmark_profile_output_3"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.tab_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 10, 411, 51))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.performance_output = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.performance_output.setFont(font)
        self.performance_output.setObjectName(_fromUtf8("performance_output"))
        self.horizontalLayout_6.addWidget(self.performance_output)
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(470, 10, 851, 64))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.python_interpreter_5 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.python_interpreter_5.setFont(font)
        self.python_interpreter_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.python_interpreter_5.setObjectName(_fromUtf8("python_interpreter_5"))
        self.verticalLayout.addWidget(self.python_interpreter_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.python_interpreter_6 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.python_interpreter_6.setFont(font)
        self.python_interpreter_6.setObjectName(_fromUtf8("python_interpreter_6"))
        self.horizontalLayout_7.addWidget(self.python_interpreter_6)
        self.python_interpreter_4 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.python_interpreter_4.setFont(font)
        self.python_interpreter_4.setObjectName(_fromUtf8("python_interpreter_4"))
        self.horizontalLayout_7.addWidget(self.python_interpreter_4)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        TabWidget.addTab(self.tab_3, _fromUtf8(""))

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget", None))
        self.benchmarks.setText(_translate("TabWidget", "Sample benchmarks", None))
        self.benchmark_profiles_2.setText(_translate("TabWidget", "Benchmark profiles", None))
        self.chart_type.setText(_translate("TabWidget", "Chart type", None))
        self.python_2_cb.setText(_translate("TabWidget", "Python 2.7.12", None))
        self.python_3_cb.setText(_translate("TabWidget", "Python 3.5.2", None))
        self.bar_chart_rb.setText(_translate("TabWidget", "Bar chart", None))
        self.python_interpreter.setText(_translate("TabWidget", "Python interpreter", None))
        self.benchmark_profile_time_rb.setText(_translate("TabWidget", "Linux time", None))
        self.iterations.setText(_translate("TabWidget", "Iterations (not implemented yet)", None))
        self.analyze_button.setText(_translate("TabWidget", "Analyze", None))
        self.benchmark_exceptions_rb.setText(_translate("TabWidget", "Handling exceptions", None))
        self.benchmark_list_compr_rb.setText(_translate("TabWidget", "List comprehension", None))
        self.benchmark_generators_rb.setText(_translate("TabWidget", "Generators", None))
        self.benchmarks_2.setText(_translate("TabWidget", "Custom benchmarks", None))
        self.load_file_button.setText(_translate("TabWidget", "Choose Python file", None))
        self.front_image.setText(_translate("TabWidget", "TextLabel", None))
        self.python_interpreter_7.setText(_translate("TabWidget", "Python bytecode analyzer", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Configuration", None))
        self.python_interpreter_2.setText(_translate("TabWidget", "Python 2.7.12 ", None))
        self.python_interpreter_3.setText(_translate("TabWidget", "Python 3.5.2", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), _translate("TabWidget", "Bytecode", None))
        self.chart_label.setText(_translate("TabWidget", "TextLabel", None))
        self.performance_output.setText(_translate("TabWidget", "Performance output", None))
        self.python_interpreter_5.setText(_translate("TabWidget", "Benchmark profile ", None))
        self.python_interpreter_6.setText(_translate("TabWidget", "Python 2.7.12 ", None))
        self.python_interpreter_4.setText(_translate("TabWidget", "Python 3.5.2", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_3), _translate("TabWidget", "Performance", None))

